name: Test Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest # node.js is already installed - github shows what each runner has installed on it
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3 # not needed on runner ubuntu-latest
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci # mpm feature 'ci' that uses the versions from the package-lock.json file
      - name: Run tests
        run: npm test
        